# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09

Parameters:

  GitHubRepository:
    Type: String

  GitHubBranchName:
    Type: String
    Default: "master"

  BatchRepositoryOwner:
    Type: String
    Default: awslabs

  BatchRepositoryName:
    Type: String
    Default: aws-batch-cbmc

  BatchRepositoryBranchName:
    Type: String
    Default: master

  ViewerRepositoryOwner:
    Type: String
    Default: markrtuttle

  ViewerRepositoryName:
    Type: String
    Default: cbmc

  ViewerRepositoryBranchName:
    Type: String
    Default: master

  S3BucketSuffix:
    Type: String
    Default: "cbmc"
    Description: "S3 bucket will be AccountId-Region-S3BucketSuffix"

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${S3BucketSuffix}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  S3AccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "S3 Bucket access identity"

  TheBucketPolicy2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3Bucket, "/*" ] ]
            Principal:
              CanonicalUser: !GetAtt S3AccessIdentity.S3CanonicalUserId
  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - S3Bucket
    - S3AccessIdentity
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Sub "${AWS::AccountId}-${AWS::Region}-${S3BucketSuffix}.s3.amazonaws.com"
          Id: S3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join [ "", [ "origin-access-identity/cloudfront/", !Ref S3AccessIdentity ] ]
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketName

  GitHubRepository:
    Value: !Ref GitHubRepository
    Export:
      Name: GitHubRepository
  GitHubBranchName:
    Value: !Ref GitHubBranchName
    Export:
      Name: GitHubBranchName

  BatchRepositoryOwner:
    Value: !Ref BatchRepositoryOwner
    Export:
      Name: BatchRepositoryOwner
  BatchRepositoryName:
    Value: !Ref BatchRepositoryName
    Export:
      Name: BatchRepositoryName
  BatchRepositoryBranchName:
    Value: !Ref BatchRepositoryBranchName
    Export:
      Name: BatchRepositoryBranchName

  ViewerRepositoryOwner:
    Value: !Ref ViewerRepositoryOwner
    Export:
      Name: ViewerRepositoryOwner
  ViewerRepositoryName:
    Value: !Ref ViewerRepositoryName
    Export:
      Name: ViewerRepositoryName
  ViewerRepositoryBranchName:
    Value: !Ref ViewerRepositoryBranchName
    Export:
      Name: ViewerRepositoryBranchName

