# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09

Parameters:

  BatchRepositoryOwner:
    Type: String
    Default: awslabs

  BatchRepositoryName:
    Type: String
    Default: aws-batch-cbmc

  BatchRepositoryBranchName:
    Type: String
    Default: master

  ViewerRepositoryOwner:
    Type: String
    Default: diffblue

  ViewerRepositoryName:
    Type: String
    Default: cbmc

  ViewerRepositoryBranchName:
    Type: String
    Default: cbmc-viewer

  S3BucketSuffix:
    Type: String
    Default: "cbmc"
    Description: "S3 bucket will be AccountId-Region-S3BucketSuffix"

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${S3BucketSuffix}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketName

  BatchRepositoryOwner:
    Value: !Ref BatchRepositoryOwner
    Export:
      Name: BatchRepositoryOwner
  BatchRepositoryName:
    Value: !Ref BatchRepositoryName
    Export:
      Name: BatchRepositoryName
  BatchRepositoryBranchName:
    Value: !Ref BatchRepositoryBranchName
    Export:
      Name: BatchRepositoryBranchName

  ViewerRepositoryOwner:
    Value: !Ref ViewerRepositoryOwner
    Export:
      Name: ViewerRepositoryOwner
  ViewerRepositoryName:
    Value: !Ref ViewerRepositoryName
    Export:
      Name: ViewerRepositoryName
  ViewerRepositoryBranchName:
    Value: !Ref ViewerRepositoryBranchName
    Export:
      Name: ViewerRepositoryBranchName

