#!/usr/bin/env python3

# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import argparse
import boto3

from aws_managers import CloudformationStack


def create_parser():
    arg = argparse.ArgumentParser(description='Get AWS stack output values.')

    arg.add_argument('--profile',
                     metavar='NAME',
                     help='AWS account profile name'
                    )
    arg.add_argument('--stack-name',
                     metavar='STACK',
                     help='AWS stack name'
                    )
    arg.add_argument('--output-name',
                     metavar='OUTPUT',
                     help='AWS stack output name'
                    )
    return arg

def main():
    args = create_parser().parse_args()
    session = boto3.session.Session(profile_name=args.profile)
    stacks = CloudformationStack.Stacks(session)
    result = stacks.get_output(args.output_name, args.stack_name)
    print(result)

if __name__ == '__main__':
    main()
